import os
import json
import re
import asyncio
from typing import List, Dict, Any, TypedDict, Optional
from pydantic import BaseModel, Field
import networkx as nx
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from dotenv import load_dotenv
from neo4j import GraphDatabase

# Load env variables
load_dotenv()

# ==========================================
# 1. Pydantic Models for Structured Output
# ==========================================

class BankAccount(BaseModel):
    bank_name: Optional[str] = Field(None, description="Name of the bank in Thai or English (e.g., กสิกรไทย, ไทยพาณิชย์, SCB, KBank, กรุงไทย)")
    account_number: Optional[str] = Field(None, description="Bank account number (digits only, remove spaces or dashes)")
    owner_name: Optional[str] = Field(None, description="Name of the bank account owner (destination account for the scam transfers)")

class ScammerSocial(BaseModel):
    platform: Optional[str] = Field(None, description="Platform used (e.g., Line, Facebook, Twitter/X, TikTok, Web, Messenger)")
    account_name: Optional[str] = Field(None, description="Display name, page name, or username of the scammer profile")
    url_or_id: Optional[str] = Field(None, description="Line ID, Facebook Page URL, TikTok username, or website link")

class ScammerEntity(BaseModel):
    scammer_names: List[str] = Field(default_factory=list, description="Names, aliases, or usernames used by the scammer(s)")
    bank_accounts: List[BankAccount] = Field(default_factory=list, description="Destination bank accounts used for receiving transfers from the victim")
    social_channels: List[ScammerSocial] = Field(default_factory=list, description="Social media accounts, groups, pages, or messaging contacts used to scam the victim")
    phones: List[str] = Field(default_factory=list, description="Phone numbers used by the scammer to contact or threat the victim")
    scam_type: Optional[str] = Field(None, description="Type/category of scam (e.g., ticket purchase, investment task, blackmail/sextortion, online shopping)")
    damage_amount: Optional[float] = Field(None, description="Total financial loss of the victim in Thai Baht (THB)")
    scam_summary: Optional[str] = Field(None, description="Brief 1-2 sentence summary of the scam method used in this case")

# ==========================================
# 2. LangGraph State Definition
# ==========================================

class AgentState(TypedDict):
    cases: List[Dict[str, Any]]                # List of all input cases from JSON
    current_index: int                         # Index of case currently being processed
    extracted_entities: List[Dict[str, Any]]    # Extracted scammer entities per case
    blacklist: List[Dict[str, Any]]            # Consolidated blacklist database entries
    graph_data: Dict[str, Any]                 # Dict of nodes and edges
    status: str                                # Current execution status message
    temp_extraction: Optional[Dict[str, Any]]  # Temporary holding area for current case extraction
    reflection_attempts: int                   # Attempt count for reflexion loop
    reflection_feedback: str                   # Validation feedback to guide correction

# Pydantic schema for reflexion self-assessment
class ExtractionReview(BaseModel):
    is_valid: bool = Field(..., description="True if the extracted details are fully accurate and make sense, False if there are errors or contradictions")
    feedback: str = Field("", description="Detailed explanation of what needs to be corrected, or empty if fully correct")

# ==========================================
# 3. LangGraph Nodes & Helper Functions
# ==========================================

def validate_and_parse_json(raw_text: str, pydantic_model) -> dict:
    """
    Cleans raw text, extracts any JSON blocks (handles markdown blocks like ```json ... ```),
    and validates it against the given Pydantic model.
    Raises ValueError with validation error description if invalid.
    """
    if not raw_text:
        raise ValueError("Empty response received from LLM.")
        
    cleaned_text = raw_text.strip()
    
    # Remove <think>...</think> tags which are generated by reasoning models
    cleaned_text = re.sub(r"<think>.*?</think>", "", cleaned_text, flags=re.DOTALL).strip()

    # Remove markdown code block fences if present
    if cleaned_text.startswith("```"):
        match = re.search(r"```(?:json)?\s*(.*?)\s*```", cleaned_text, re.DOTALL)
        if match:
            cleaned_text = match.group(1).strip()
            
    # Simple JSON search fallback in case there is trailing text outside code blocks
    if not (cleaned_text.startswith("{") and cleaned_text.endswith("}")):
        match = re.search(r"(\{.*\})", cleaned_text, re.DOTALL)
        if match:
            cleaned_text = match.group(1).strip()
            
    try:
        data = json.loads(cleaned_text)
    except json.JSONDecodeError as e:
        raise ValueError(f"Invalid JSON Format: {str(e)}\nRaw Response: {raw_text}")
        
    # Validate using Pydantic
    try:
        validated_obj = pydantic_model(**data)
        return validated_obj.model_dump()
    except Exception as e:
        raise ValueError(f"JSON schema validation failed: {str(e)}")

def is_similar_to_accuser(name: str, accuser: str) -> bool:
    """
    Checks if a name is highly similar to the accuser's name using fuzzy matching (SequenceMatcher).
    Helps prevent slight spelling variations of the victim's name from leaking into scammer data.
    """
    if not name or not accuser:
        return False
        
    import difflib
    n = name.strip().lower()
    a = accuser.strip().lower()
    
    # Pre-clean: strip common titles
    titles = ["นางสาว", "นาง", "นาย", "ด.ญ.", "ด.ช.", "น.ส.", "mr.", "ms.", "mrs."]
    for title in titles:
        n = n.replace(title, "").strip()
        a = a.replace(title, "").strip()
        
    # Check if one is a substring of the other or vice versa
    if n in a or a in n:
        return True
        
    # Calculate similarity ratio
    ratio = difflib.SequenceMatcher(None, n, a).ratio()
    return ratio > 0.75  # 75% threshold is highly effective for Thai name spelling variations

def sanitize_extracted_data(extracted_data: dict, accuser: str) -> dict:
    """
    Programmatically sanitizes the extracted data to prevent victim info leakage (leakage guardrail)
    and strips placeholder mock data copied from prompts by smaller local LLMs.
    """
    if not extracted_data:
        return extracted_data
        
    accuser_clean = accuser.strip().lower()
    ignored_placeholders = ["สมชาย สมถาวร", "0123456789", "ชื่อเจ้าของบัญชีปลายทาง", "ชื่อมิจฉาชีพ1", "ชื่อมิจฉาชีพ2", "ชื่อธนาคาร", "เลขบัญชี", "ลิงก์หรือไอดี"]
    
    def is_placeholder(val: str) -> bool:
        if not val:
            return True
        val_clean = val.strip().lower()
        for p in ignored_placeholders:
            if p in val_clean:
                return True
        return False

    # 1. Clean scammer_names: remove victim's name or placeholder
    if "scammer_names" in extracted_data and isinstance(extracted_data["scammer_names"], list):
        filtered_names = []
        for name in extracted_data["scammer_names"]:
            if is_placeholder(name):
                print(f"[Guardrail] Automatically removed placeholder scammer name: '{name}'")
                continue
            if is_similar_to_accuser(name, accuser):
                print(f"[Guardrail] Automatically removed accuser name '{name}' (similar to '{accuser}') from scammer_names.")
                continue
            filtered_names.append(name)
        extracted_data["scammer_names"] = filtered_names
        
    # 2. Clean bank_accounts: ensure bank owner name is not the accuser or placeholder
    if "bank_accounts" in extracted_data and isinstance(extracted_data["bank_accounts"], list):
        filtered_accounts = []
        for acct in extracted_data["bank_accounts"]:
            owner = acct.get("owner_name", "")
            acct_num = acct.get("account_number", "")
            bank_name = acct.get("bank_name", "")
            
            if is_placeholder(owner) or is_placeholder(acct_num) or is_placeholder(bank_name):
                print(f"[Guardrail] Automatically removed placeholder bank account: {bank_name} - {acct_num} ({owner})")
                continue
            if owner and is_similar_to_accuser(owner, accuser):
                print(f"[Guardrail] Automatically removed bank account belonging to accuser: '{owner}' (similar to '{accuser}').")
                continue
            filtered_accounts.append(acct)
        extracted_data["bank_accounts"] = filtered_accounts
        
    # 3. Clean social channels: ensure social handles/IDs are not the accuser's name/ID or placeholders
    if "social_channels" in extracted_data and isinstance(extracted_data["social_channels"], list):
        filtered_socials = []
        for sc in extracted_data["social_channels"]:
            url_id = sc.get("url_or_id", "")
            name = sc.get("account_name", "")
            platform = sc.get("platform", "")
            
            if is_placeholder(url_id) or is_placeholder(name) or is_placeholder(platform):
                print(f"[Guardrail] Automatically removed placeholder social channel: {platform} ({name or url_id})")
                continue
            if (url_id and accuser_clean in url_id.lower()) or (name and is_similar_to_accuser(name, accuser)):
                print(f"[Guardrail] Automatically removed social channel linked to accuser '{name or url_id}'.")
                continue
            filtered_socials.append(sc)
        extracted_data["social_channels"] = filtered_socials
        
    return extracted_data

def extract_case_entities(state: AgentState) -> AgentState:
    """Node to extract scammer entities from a case transcript using Gemini or Local LLM."""
    idx = state["current_index"]
    cases = state["cases"]
    attempts = state.get("reflection_attempts", 0)
    feedback = state.get("reflection_feedback", "")
    
    if idx >= len(cases):
        return {**state, "status": "All cases processed"}
        
    case = cases[idx]
    case_id = case.get("case_id")
    accuser = case.get("accuser")
    ai_summary = case.get("case_ai_summary", "")
    
    provider = os.getenv("LLM_PROVIDER", "gemini").lower()
    
    print(f"\n[Agent] Extracting entities for Case {idx+1}/{len(cases)} (ID: {case_id[:6]}..., Accuser: {accuser}) - Attempt {attempts+1} ({provider} mode)...")
    
    extracted_data = None
    parse_error = ""
    
    if provider == "local":
        try:
            from langchain_ollama import ChatOllama
            base_url = os.getenv("LLM_BASE_URL", "http://localhost:11434/v1")
            model_name = os.getenv("LLM_MODEL", "qwen2.5:7b")
            
            # Base URL for native Ollama API is without "/v1"
            native_base_url = base_url.replace("/v1", "") if base_url.endswith("/v1") else base_url
            
            print(f"[Debug] [Step 1/3] Connecting to native Ollama server '{model_name}' at {native_base_url}...")
            # Use native ChatOllama client
            model = ChatOllama(
                model=model_name,
                base_url=native_base_url,
                temperature=0.0,
                timeout=300         # 5 minutes client-side timeout to allow model loading
            )
            
            structured_mode = os.getenv("STRUCTURED_OUTPUT_MODE", "raw_json").lower()
            
            prompt = f"""คุณคือผู้เชี่ยวชาญการวิเคราะห์คดีอาชญากรรมไซเบอร์ (Cybercrime Investigation Specialist)
จงอ่านคำสรุปคดีสอบสวน (case_ai_summary) ด้านล่างนี้ และสกัดเอนทิตี (Entities) ของมิจฉาชีพออกมาตามรูปแบบ JSON โครงสร้างที่กำหนดเท่านั้น ห้ามนำข้อมูลของผู้กล่าวหา ({accuser}) มาตอบเป็นมิจฉาชีพเด็ดขาด

ข้อมูลคดี:
- ผู้กล่าวหา: {accuser}
- รายละเอียดพฤติการณ์: {ai_summary}
"""
            if feedback:
                prompt += f"\n\n**[ข้อเสนอแนะจากการตรวจสอบในรอบก่อนหน้านี้เพื่อแก้ไข]**:\n{feedback}\nโปรดปรับปรุงผลลัพธ์การสกัดข้อมูลและหลีกเลี่ยงข้อผิดพลาดข้างต้น"
                
            prompt += """\n\nตอบกลับเป็นข้อความรูปแบบ JSON เท่านั้น โดยใช้โครงสร้างและคีย์ดังต่อไปนี้:
{
  "scammer_names": ["ชื่อมิจฉาชีพ1", "ชื่อมิจฉาชีพ2"],
  "bank_accounts": [
    {
      "bank_name": "ชื่อธนาคาร",
      "account_number": "เลขบัญชี (เฉพาะตัวเลข)",
      "owner_name": "ชื่อเจ้าของบัญชีปลายทาง"
    }
  ],
  "social_channels": [
    {
      "platform": "เช่น Line, Facebook",
      "account_name": "ชื่อบัญชี",
      "url_or_id": "ลิงก์หรือไอดี"
    }
  ],
  "phones": ["เบอร์โทรศัพท์"],
  "scam_type": "ประเภทกลโกง",
  "damage_amount": 12345.67,
  "scam_summary": "สรุปพฤติการณ์สั้นๆ"
}
"""
            # 3-Tier Fallback Architecture for Structured Output
            extracted_data = None
            
            # Tier 1: json_schema
            if structured_mode in ["auto", "json_schema"]:
                try:
                    print(f"[Debug] [Tier 1] Querying local LLM structured output (method=json_schema)...")
                    structured_model = model.with_structured_output(ScammerEntity, method="json_schema")
                    response = structured_model.invoke(prompt)
                    extracted_data = response if isinstance(response, dict) else response.model_dump()
                    print(f"[Debug] [Tier 1] json_schema output received successfully.")
                except Exception as e:
                    print(f"[Warning] Tier 1 json_schema failed: {e}. Falling back to next tier...")
            
            # Tier 2: json_mode (format="json")
            if not extracted_data and structured_mode in ["auto", "json_schema", "json_mode"]:
                try:
                    print(f"[Debug] [Tier 2] Querying local LLM with json_mode (format=json)...")
                    json_mode_model = model.bind(format="json")
                    raw_response = json_mode_model.invoke(prompt)
                    raw_text = raw_response.content if hasattr(raw_response, 'content') else str(raw_response)
                    extracted_data = validate_and_parse_json(raw_text, ScammerEntity)
                    print(f"[Debug] [Tier 2] json_mode output received and parsed successfully.")
                except Exception as e:
                    print(f"[Warning] Tier 2 json_mode failed: {e}. Falling back to Tier 3...")

            # Tier 3: raw_json (strict prompt + cleaner + pydantic)
            if not extracted_data:
                print(f"[Debug] [Tier 3] Querying local LLM raw output for entity extraction...")
                raw_response = model.invoke(prompt)
                raw_text = raw_response.content if hasattr(raw_response, 'content') else str(raw_response)
                print(f"[Debug] [Tier 3] Raw response received. Parsing JSON with Schema Validator Guardrail...")
                extracted_data = validate_and_parse_json(raw_text, ScammerEntity)
                
        except Exception as e:
            print(f"[Error] Local LLM extraction failed: {e}. Falling back to simulation...")
            parse_error = str(e)
            extracted_data = simulate_extraction(case)
            
    else:
        # Gemini Mode
        api_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")
        if not api_key or api_key == "your_gemini_api_key_here":
            print("[Warning] No valid Gemini API Key found in environment/dotenv. Simulating extraction from summary...")
            extracted_data = simulate_extraction(case)
            
            # Inject mock mistake on Attempt 1 for Case 1 to demonstrate Reflexion loop
            if idx == 0 and attempts == 0:
                print("[Mock] Intentionally injecting error: adding victim name to scammer list...")
                extracted_data["scammer_names"].append(accuser)
            elif idx == 0 and attempts == 1:
                print("[Mock] Correcting error based on feedback: removing victim name from scammer list...")
                if accuser in extracted_data["scammer_names"]:
                    extracted_data["scammer_names"].remove(accuser)
        else:
            try:
                from langchain_google_genai import ChatGoogleGenerativeAI
                model = ChatGoogleGenerativeAI(
                    model="gemini-2.5-flash",
                    google_api_key=api_key,
                    temperature=0.0
                )
                structured_model = model.with_structured_output(ScammerEntity)
                
                prompt = f"""
                คุณคือผู้เชี่ยวชาญการวิเคราะห์คดีอาชญากรรมไซเบอร์ (Cybercrime Investigation Specialist) 
                จงอ่านคำสรุปคดีสอบสวน (case_ai_summary) ต่อไปนี้ และสกัดเอนทิตี (Entities) ของมิจฉาชีพออกมาตามโครงสร้างที่กำหนด
                
                ข้อมูลคดี:
                - ผู้กล่าวหา: {accuser}
                - รายละเอียดพฤติการณ์: {ai_summary}
                """
                if feedback:
                    prompt += f"\n\n**[ข้อเสนอแนะจากการตรวจสอบในรอบก่อนหน้านี้เพื่อแก้ไข]**:\n{feedback}\nโปรดปรับปรุงผลลัพธ์การสกัดข้อมูลและหลีกเลี่ยงข้อผิดพลาดข้างต้น"
                
                response = structured_model.invoke(prompt)
                if isinstance(response, dict):
                    extracted_data = response
                else:
                    extracted_data = response.model_dump()
                
            except Exception as e:
                print(f"[Error] Gemini API failed: {e}. Falling back to simulation...")
                parse_error = str(e)
                extracted_data = simulate_extraction(case)
                
    # Run Leakage and Blacklist Filters
    if extracted_data:
        extracted_data = sanitize_extracted_data(extracted_data, accuser)
        
    # Include case metadata in the result
    extracted_data["case_id"] = case_id
    extracted_data["accuser"] = accuser
    
    if parse_error:
        extracted_data["parse_error"] = parse_error
        
    return {
        **state,
        "temp_extraction": extracted_data,
        "status": f"Extracted case {idx+1}/{len(cases)} (Attempt {attempts+1})"
    }

def reflect_case_entities(state: AgentState) -> AgentState:
    """Node to audit/self-reflect on the extracted entities and verify correctness with Loop Guard."""
    idx = state["current_index"]
    case = state["cases"][idx]
    accuser = case.get("accuser")
    ai_summary = case.get("case_ai_summary", "")
    extracted_data = state["temp_extraction"]
    attempts = state.get("reflection_attempts", 0)
    
    print(f"[Agent/Reflector] Auditing and verifying extracted entities for Case {idx+1}...")
    
    provider = os.getenv("LLM_PROVIDER", "gemini").lower()
    is_valid = True
    feedback = ""
    
    # 1. Check if there was a parsing/validation error in extraction node
    if extracted_data and "parse_error" in extracted_data:
        is_valid = False
        feedback += f"การดึงข้อมูลผิดพลาดเนื่องจากฟอร์แมต JSON: {extracted_data['parse_error']}. "
        
    # 2. Pre-audit using programmatic rules (Python Guardrails)
    accuser_clean = accuser.strip().lower()
    if extracted_data:
        for name in extracted_data.get("scammer_names", []):
            if name.strip().lower() == accuser_clean or accuser_clean in name.strip().lower():
                is_valid = False
                feedback += f"ตรวจพบชื่อผู้เสียหาย '{name}' ปะปนอยู่ในรายชื่อมิจฉาชีพ (scammer_names). "
                
        for acct in extracted_data.get("bank_accounts", []):
            owner = acct.get("owner_name", "")
            if owner and (owner.strip().lower() == accuser_clean or accuser_clean in owner.strip().lower()):
                is_valid = False
                feedback += f"ตรวจพบว่าบัญชีธนาคารปลายทาง {acct.get('account_number')} มีชื่อเจ้าของเป็นผู้เสียหาย '{owner}'. "
                
    if not is_valid:
        print(f"❌ [Guardrail] Programmatic Audit Failed: {feedback}")
    else:
        # 3. Model-based audit if programmatic checks pass
        if provider == "local":
            try:
                from langchain_ollama import ChatOllama
                base_url = os.getenv("LLM_BASE_URL", "http://localhost:11434/v1")
                model_name = os.getenv("LLM_MODEL", "qwen2.5:7b")
                
                # Base URL for native Ollama API is without "/v1"
                native_base_url = base_url.replace("/v1", "") if base_url.endswith("/v1") else base_url
                
                print(f"[Debug] [Step 1/2] Connecting to native Ollama server '{model_name}' at {native_base_url} for reflection audit...")
                # Use native ChatOllama client
                model = ChatOllama(
                    model=model_name,
                    base_url=native_base_url,
                    temperature=0.0,
                    timeout=300         # 5 minutes client-side timeout to allow model loading
                )
                
                structured_mode = os.getenv("STRUCTURED_OUTPUT_MODE", "raw_json").lower()
                
                prompt = f"""คุณคือหัวหน้าฝ่ายตรวจสอบอิสระ (Independent Cyber Investigator Auditor)
หน้าที่ของคุณคือการจับผิดและตรวจสอบความถูกต้องของข้อมูลที่สกัดมาอย่างเข้มงวดที่สุด! ห้ามเออออคล้อยตามผลลัพธ์เดิมเด็ดขาด

จงเปรียบเทียบข้อมูลสรุปคดีดั้งเดิม กับ ข้อมูลที่ระบบสกัดมา (Extracted Data) ด้านล่างนี้:

ข้อมูลคดีดั้งเดิม:
- ผู้กล่าวหา: {accuser}
- พฤติการณ์คดี: {ai_summary}

ข้อมูลที่ระบบสกัดได้:
- ชื่อผู้เสียหาย: {accuser}
- รายชื่อมิจฉาชีพ/ผู้ต้องสงสัย (scammer_names): {extracted_data.get('scammer_names')}
- บัญชีธนาคารปลายทาง (bank_accounts): {extracted_data.get('bank_accounts')}
- ช่องทางการสื่อสารของคนร้าย (social_channels): {extracted_data.get('social_channels')}
- เบอร์โทรศัพท์ของคนร้าย (phones): {extracted_data.get('phones')}
- ความเสียหายรวม (damage_amount): {extracted_data.get('damage_amount')}

กฎการตรวจสอบความถูกต้องอย่างเข้มงวด:
1. บัญชีธนาคารปลายทางที่โอนไป (bank_accounts) ต้องเป็นบัญชีของมิจฉาชีพเท่านั้น ห้ามดึงข้อมูลบัญชี/ชื่อของผู้กล่าวหา ({accuser}) มาปนเปื้อนเด็ดขาด
2. รายชื่อมิจฉาชีพ (scammer_names) และบัญชีโซเชียลมีเดีย ต้องไม่ใช่ชื่อหรือไอดีของผู้เสียหาย
3. เบอร์โทรศัพท์ (phones) ต้องเป็นเบอร์ของคนร้ายที่โทรเข้ามาหลอกลวง/ข่มขู่ ห้ามนำเบอร์โทรของผู้เสียหายมาใส่

ตอบกลับเฉพาะในรูปแบบ JSON ที่ถูกต้องตามคีย์ดังนี้เท่านั้น:
{{
  "is_valid": true หรือ false,
  "feedback": "คำแนะนำในการแก้ไขสกัดใหม่ (ปล่อยว่างถ้าถูกต้องทั้งหมด)"
}}
"""
                review_data = None
                
                # Tier 1: json_schema
                if structured_mode in ["auto", "json_schema"]:
                    try:
                        print(f"[Debug] [Tier 1] Querying local LLM structured output for validation review...")
                        structured_auditor = model.with_structured_output(ExtractionReview, method="json_schema")
                        review = structured_auditor.invoke(prompt)
                        review_data = review if isinstance(review, dict) else review.model_dump()
                        print(f"[Debug] [Tier 1] Review received successfully.")
                    except Exception as e:
                        print(f"[Warning] Tier 1 json_schema auditor failed: {e}. Falling back to next tier...")
                
                # Tier 2: json_mode
                if not review_data and structured_mode in ["auto", "json_schema", "json_mode"]:
                    try:
                        print(f"[Debug] [Tier 2] Querying local LLM with json_mode for validation review...")
                        json_mode_model = model.bind(format="json")
                        raw_response = json_mode_model.invoke(prompt)
                        raw_text = raw_response.content if hasattr(raw_response, 'content') else str(raw_response)
                        review_data = validate_and_parse_json(raw_text, ExtractionReview)
                        print(f"[Debug] [Tier 2] json_mode review parsed successfully.")
                    except Exception as e:
                        print(f"[Warning] Tier 2 json_mode auditor failed: {e}. Falling back to Tier 3...")

                # Tier 3: raw_json
                if not review_data:
                    print(f"[Debug] [Tier 3] Querying local LLM raw output for validation review...")
                    raw_response = model.invoke(prompt)
                    raw_text = raw_response.content if hasattr(raw_response, 'content') else str(raw_response)
                    print(f"[Debug] [Tier 3] Raw response received. Parsing JSON with Schema Validator Guardrail...")
                    review_data = validate_and_parse_json(raw_text, ExtractionReview)
                    
                is_valid = review_data.get("is_valid", True)
                feedback = review_data.get("feedback", "")
                
            except Exception as e:
                print(f"[Reflector] Local model audit failed: {e}. Defaulting to auto-approve.")
                is_valid = True
                feedback = ""
        else:
            # Gemini Mode
            api_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")
            if not api_key or api_key == "your_gemini_api_key_here":
                is_valid = True
                feedback = ""
                if idx == 0 and accuser in extracted_data.get("scammer_names", []):
                    is_valid = False
                    feedback = f"ตรวจพบชื่อผู้กล่าวหา '{accuser}' ปะปนอยู่ในรายชื่อมิจฉาชีพ (scammer_names) ซึ่งไม่ถูกต้องตามกฎการตรวจสอบ!"
            else:
                try:
                    from langchain_google_genai import ChatGoogleGenerativeAI
                    model = ChatGoogleGenerativeAI(
                        model="gemini-2.5-flash",
                        google_api_key=api_key,
                        temperature=0.0
                    )
                    structured_auditor = model.with_structured_output(ExtractionReview)
                    
                    prompt = f"""
                    คุณคือหัวหน้าฝ่ายตรวจสอบ (Lead Auditor / Cyber Investigator) 
                    จงเปรียบเทียบคำสรุปคดีดั้งเดิม กับ ข้อมูลที่ระบบสกัดมา (Extracted Data) ว่าความสัมพันธ์และเอนทิตีสมเหตุสมผลหรือไม่
                    
                    ข้อมูลคดีดั้งเดิม:
                    - ผู้กล่าวหา: {accuser}
                    - พฤติการณ์คดี: {ai_summary}
                    
                    ข้อมูลที่ระบบสกัดได้:
                    - ชื่อผู้เสียหาย: {accuser}
                    - รายชื่อมิจฉาชีพ/ผู้ต้องสงสัย (scammer_names): {extracted_data.get('scammer_names')}
                    - บัญชีธนาคารปลายทาง (bank_accounts): {extracted_data.get('bank_accounts')}
                    - ช่องทางการสื่อสารของคนร้าย (social_channels): {extracted_data.get('social_channels')}
                    - เบอร์โทรศัพท์ของคนร้าย (phones): {extracted_data.get('phones')}
                    - ความเสียหายรวม (damage_amount): {extracted_data.get('damage_amount')}
                    
                    กฎการตรวจสอบความถูกต้อง (Verification Rules):
                    1. บัญชีธนาคาร/ชื่อเจ้าของบัญชีปลายทางที่โอนไป (bank_accounts) ต้องเป็นบัญชีของคนร้าย (บัญชีม้า) ห้ามดึงบัญชีหรือชื่อจริงของผู้กล่าวหา ({accuser}) มาสวมรอย
                    2. รายชื่อมิจฉาชีพ (scammer_names) และบัญชีโซเชียลมีเดีย ต้องไม่ใช่ชื่อหรือไอดีของผู้เสียหาย
                    3. เบอร์โทรศัพท์ (phones) ต้องเป็นเบอร์ของคนร้ายที่โทรเข้ามาหลอกลวง/ข่มขู่ ห้ามนำเบอร์โทรของผู้เสียหายมาใส่
                    4. ตรวจสอบว่ามีชื่อผู้ต้องสงสัยสลับกับชื่อเจ้าของบัญชีธนาคารปลายทางหรือไม่ (ทั้งคู่เป็นคนร้ายได้ แต่ต้องไม่เอาข้อมูลผู้เสียหายมาปน)
                    
                    ผลลัพธ์การตรวจสอบต้องตอบกลับในรูปแบบ JSON ตามโมเดล:
                    - is_valid: True (ถ้าสมบูรณ์ถูกต้อง) หรือ False (ถ้าพบจุดผิดพลาดหรือจุดที่ปะปนข้อมูลผู้เสียหาย)
                    - feedback: อธิบายจุดที่สกัดผิดเพื่อให้ทีมงานสกัดรอบถัดไปแก้ไขได้ถูกต้อง (ถ้า is_valid เป็น True ให้ใส่ว่างเปล่า)
                    """
                    
                    review = structured_auditor.invoke(prompt)
                    if isinstance(review, dict):
                        review_data = review
                    else:
                        review_data = review.model_dump()
                        
                    is_valid = review_data.get("is_valid", True)
                    feedback = review_data.get("feedback", "")
                except Exception as e:
                    print(f"[Reflector] Audit model failed: {e}. Defaulting to auto-approve.")
                    is_valid = True
                    feedback = ""
                    
    # Strict Loop Guard / Max Retry = 1
    max_retries = 1
    if not is_valid and attempts < max_retries:
        print(f"❌ [Reflector] Audit Failed (Attempt {attempts+1}/{max_retries+1}): {feedback}. Retrying...")
        return {
            **state,
            "reflection_feedback": feedback,
            "reflection_attempts": attempts + 1,
            "status": f"Audit failed: {feedback}. Retrying Case {idx+1}..."
        }
    else:
        if not is_valid:
            print(f"⚠ [Reflector] Audit Failed but max retries ({max_retries}) reached. Proceeding with current data.")
            
        else:
            print("✔ [Reflector] Audit Passed!")
            
        # Clean up parse error and commit the temporary extraction
        if extracted_data and "parse_error" in extracted_data:
            del extracted_data["parse_error"]
            
        extracted = list(state.get("extracted_entities", []))
        if state.get("temp_extraction"):
            extracted.append(state["temp_extraction"])
            
        return {
            **state,
            "extracted_entities": extracted,
            "current_index": idx + 1,
            "reflection_attempts": 0,
            "reflection_feedback": "",
            "temp_extraction": None,
            "status": f"Processed case {idx+1}/{len(state['cases'])}"
        }

def route_reflection(state: AgentState) -> str:
    """Conditional router function to determine if extraction should loop back or move on (read-only)."""
    feedback = state.get("reflection_feedback", "")
    idx = state["current_index"]
    cases = state["cases"]
    
    if feedback:
        # We set reflection_feedback, meaning the auditor requested a retry
        return "retry"
    else:
        # No feedback means we successfully committed this case and incremented current_index
        if idx < len(cases):
            return "continue"
        return "consolidate"

def simulate_extraction(case: Dict[str, Any]) -> Dict[str, Any]:
    """Helper mock function to parse summary via Regex in case Gemini API is not configured."""
    summary = case.get("case_ai_summary", "")
    accuser = case.get("accuser", "")
    
    # Simple regex fallbacks for demonstration when API Key is missing
    # 1. Damage amount extraction
    damage_match = re.search(r'(?:จำนวนเงิน|เป็นเงิน|มูลค่ารวมทั้งสิ้น|ความเสียหายเป็นเงิน|โอนทั้งสิ้น)\s*([\d,]+)\s*บาท', summary)
    damage = float(damage_match.group(1).replace(",", "")) if damage_match else 0.0
    
    # 2. Bank accounts extraction (simple match)
    bank_accounts = []
    # Find bank account details in lines starting with '-'
    transfers = re.findall(r'ธนาคาร([ก-๙a-zA-Z\s]+)\s+เลขที่บัญชี\s*([\d\-]+)\s+ชื่อบัญชี\s*([ก-๙a-zA-Z\s]+)(?=เมื่อ|\n|$)', summary)
    for bank, acct, name in transfers:
        bank_accounts.append({
            "bank_name": bank.strip(),
            "account_number": acct.replace("-", "").strip(),
            "owner_name": name.strip()
        })
        
    # 3. Social media extraction
    socials = []
    if "LINE" in summary.upper():
        socials.append({"platform": "Line", "account_name": "LINE Contact", "url_or_id": "LINE"})
    if "Facebook" in summary or "เฟซบุ๊ก" in summary:
        socials.append({"platform": "Facebook", "account_name": "Facebook Profile", "url_or_id": "Facebook"})
    if "Twitter" in summary or "ทวิตเตอร์" in summary:
        socials.append({"platform": "Twitter/X", "account_name": "Twitter Profile", "url_or_id": "Twitter/X"})
        
    # 4. Scam type
    scam_type = "Online Scam"
    if "บัตรคอนเสิร์ต" in summary:
        scam_type = "Concert Ticket Scam"
    elif "รีวิวสินค้า" in summary or "ทำภารกิจ" in summary:
        scam_type = "Job/Task Scam"
    elif "แบล็คเมล์" in summary or "คลิปส่วนตัว" in summary:
        scam_type = "Blackmail/Sextortion"
        
    # 5. Phones
    phones = re.findall(r'\b0\d{8,9}\b', summary)
    
    # 6. Scammer name (often suspects match)
    scammer_names = []
    suspects_raw = case.get("suspect", "")
    if suspects_raw and "ระหว่างสอบสวน" not in suspects_raw:
        scammer_names = [s.strip() for s in re.split(r'\s{2,}|,', suspects_raw) if s.strip()]
        
    return {
        "scammer_names": scammer_names,
        "bank_accounts": bank_accounts,
        "social_channels": socials,
        "phones": list(set(phones)),
        "scam_type": scam_type,
        "damage_amount": damage,
        "scam_summary": f"Scam case involving {scam_type} targeting {accuser}."
    }

def check_loop_condition(state: AgentState) -> str:
    """Conditional router function to check if more cases need processing."""
    if state["current_index"] < len(state["cases"]):
        return "continue"
    return "consolidate"

def consolidate_blacklist(state: AgentState) -> AgentState:
    """Node to aggregate extracted entities into a structured blacklist database."""
    print("\n[Agent] Consolidating blacklist database...")
    extracted = state["extracted_entities"]
    
    # Unique banks, socials, phones, names
    unique_bank_accounts = {}
    unique_socials = {}
    unique_phones = set()
    unique_scammers = {}
    
    for case_data in extracted:
        case_id = case_data.get("case_id")
        
        # 1. Process Bank Accounts
        for bank in case_data.get("bank_accounts", []):
            acct_num = bank.get("account_number")
            owner = bank.get("owner_name")
            bank_name = bank.get("bank_name")
            if acct_num and owner:
                key = f"{bank_name}_{acct_num}"
                if key not in unique_bank_accounts:
                    unique_bank_accounts[key] = {
                        "bank_name": bank_name,
                        "account_number": acct_num,
                        "owner_name": owner,
                        "linked_cases": [case_id],
                        "associated_scammers": list(case_data.get("scammer_names", []))
                    }
                else:
                    if case_id not in unique_bank_accounts[key]["linked_cases"]:
                        unique_bank_accounts[key]["linked_cases"].append(case_id)
                    # Merge associated scammers
                    for s_name in case_data.get("scammer_names", []):
                        if s_name not in unique_bank_accounts[key]["associated_scammers"]:
                            unique_bank_accounts[key]["associated_scammers"].append(s_name)
                            
        # 2. Process Social Profiles
        for social in case_data.get("social_channels", []):
            platform = social.get("platform")
            val = social.get("url_or_id")
            name = social.get("account_name")
            if val:
                key = f"{platform}_{val}"
                if key not in unique_socials:
                    unique_socials[key] = {
                        "platform": platform,
                        "url_or_id": val,
                        "account_name": name,
                        "linked_cases": [case_id]
                    }
                else:
                    if case_id not in unique_socials[key]["linked_cases"]:
                        unique_socials[key]["linked_cases"].append(case_id)
                        
        # 3. Process Phones
        for phone in case_data.get("phones", []):
            unique_phones.add(phone)
            
        # 4. Process Scammer Names
        for name in case_data.get("scammer_names", []):
            if name not in unique_scammers:
                unique_scammers[name] = {
                    "name": name,
                    "linked_cases": [case_id],
                    "associated_banks": []
                }
            else:
                if case_id not in unique_scammers[name]["linked_cases"]:
                    unique_scammers[name]["linked_cases"].append(case_id)
                    
            # Link banks used in this case to this scammer name
            for bank in case_data.get("bank_accounts", []):
                acct_num = bank.get("account_number")
                bank_name = bank.get("bank_name")
                if acct_num:
                    b_str = f"{bank_name} - {acct_num}"
                    if b_str not in unique_scammers[name]["associated_banks"]:
                        unique_scammers[name]["associated_banks"].append(b_str)
                        
    # Structure the blacklist entries
    blacklist = {
        "bank_accounts": list(unique_bank_accounts.values()),
        "social_accounts": list(unique_socials.values()),
        "phone_numbers": list(unique_phones),
        "scammer_profiles": list(unique_scammers.values())
    }
    
    # Save the blacklist JSON file in the workspace
    workspace_dir = "/Users/supanus/Desktop/oneforce/extrack_scammer"
    blacklist_path = os.path.join(workspace_dir, "blacklist.json")
    with open(blacklist_path, "w", encoding="utf-8") as f:
        json.dump(blacklist, f, indent=2, ensure_ascii=False)
        
    print(f"[Agent] Blacklist saved with {len(blacklist['bank_accounts'])} bank accounts and {len(blacklist['scammer_profiles'])} scammer profiles.")
    
    return {
        **state,
        "blacklist": [blacklist],
        "status": "Blacklist consolidated successfully"
    }

def build_network_graph(state: AgentState) -> AgentState:
    """Node to parse the extracted entities and build raw NetworkX nodes and edges matching Neo4j schema with properties."""
    print("\n[Agent] Building network graph structure (Neo4j-style with properties)...")
    extracted = state["extracted_entities"]
    
    nodes = []
    edges = []
    
    # Maintain node registries to prevent duplicate definitions
    seen_nodes = set()
    
    def add_node(node_id: str, label: str, node_type: str, properties: Dict[str, Any] = None):
        if node_id not in seen_nodes:
            seen_nodes.add(node_id)
            nodes.append({
                "id": node_id,
                "label": label,
                "type": node_type,
                "properties": properties or {}
            })
            
    def add_edge(source: str, target: str, rel_type: str, properties: Dict[str, Any] = None):
        edges.append({
            "source": source,
            "target": target,
            "relation": rel_type,
            "properties": properties or {}
        })
        
    for case_data in extracted:
        case_id = case_data.get("case_id")
        accuser = case_data.get("accuser")
        scam_type = case_data.get("scam_type", "Online Scam")
        damage = case_data.get("damage_amount", 0.0)
        
        # We can find the station info from the original cases list
        orig_case = next((c for c in state["cases"] if c.get("case_id") == case_id), {})
        station_name = orig_case.get("station", "")
        audio_url = orig_case.get("audio_url", "")
        
        # 1. Case Node (Rose Red)
        case_node_id = f"case_{case_id}"
        # Formatting loss amount for label display, e.g., 57K THB
        loss_label = f"{damage/1000:.1f}k THB" if damage >= 1000 else f"{damage:.0f} THB"
        case_label = f"Case: {case_id[:6]}...\n({loss_label})"
        
        add_node(case_node_id, case_label, "case", {
            "case_id": case_id,
            "scam_type": scam_type,
            "damage_amount": damage,
            "station": station_name
        })
        
        # 2. Victim Person Node (Green)
        if accuser:
            victim_node_id = f"person_{accuser}"
            add_node(victim_node_id, accuser, "person", {
                "name": accuser,
                "role": "victim"
            })
            add_edge(victim_node_id, case_node_id, "VICTIM_IN", {"role": "victim"})
            
        # 3. Suspect Person Node (Green) - "ผู้ต้องสงสัย"
        for name in case_data.get("scammer_names", []):
            suspect_node_id = f"person_{name}"
            add_node(suspect_node_id, name, "person", {
                "name": name,
                "role": "suspect"
            })
            add_edge(case_node_id, suspect_node_id, "SCAMMED_BY", {"role": "suspect"})
            
        # 4. Bank Account Node (Hot Pink) - "FinancialAccount"
        for bank in case_data.get("bank_accounts", []):
            acct_num = bank.get("account_number")
            bank_name = bank.get("bank_name")
            owner = bank.get("owner_name")
            if acct_num:
                bank_node_id = f"bank_{acct_num}"
                label = f"{bank_name}: {acct_num}"
                add_node(bank_node_id, label, "bank", {
                    "bank_name": bank_name,
                    "account_number": acct_num,
                    "owner": owner
                })
                # Link Case -> Bank Account
                add_edge(case_node_id, bank_node_id, "TRANSFERRED_TO", {
                    "bank_name": bank_name,
                    "account_number": acct_num,
                    "damage_amount": damage
                })
                
                # 5. Defendant / Account Owner Node (Green) - "จำเลย/เจ้าของบัญชี"
                if owner:
                    owner_node_id = f"person_{owner}"
                    add_node(owner_node_id, owner, "person", {
                        "name": owner,
                        "role": "defendant"
                    })
                    # Bank Account is owned by this person
                    add_edge(bank_node_id, owner_node_id, "OWNED_BY", {"role": "defendant"})
                    
        # 6. Social Channels (Orange) - "OnlineAccount"
        for social in case_data.get("social_channels", []):
            val = social.get("url_or_id")
            platform = social.get("platform")
            name = social.get("account_name")
            if val:
                channel_node_id = f"social_{platform}_{val}"
                label = f"{platform}: {name or val}"
                add_node(channel_node_id, label, "channel", {
                    "platform": platform,
                    "url_or_id": val,
                    "account_name": name
                })
                add_edge(case_node_id, channel_node_id, "CONTACTED_THROUGH", {
                    "platform": platform,
                    "url_or_id": val
                })
                
        # 7. Evidence Node (Sky Blue) - "Evidence"
        if audio_url:
            evidence_node_id = f"evidence_{case_id}"
            add_node(evidence_node_id, "Audio Recording", "evidence", {
                "audio_url": audio_url,
                "type": "audio"
            })
            add_edge(case_node_id, evidence_node_id, "HAS_EVIDENCE", {
                "type": "audio"
            })
            
        # 8. Location Node (Light Green) - "Location"
        if station_name:
            loc_node_id = f"location_{station_name}"
            add_node(loc_node_id, station_name, "location", {
                "station_name": station_name
            })
            add_edge(case_node_id, loc_node_id, "OCCURRED_AT", {
                "station_name": station_name
            })
            
    graph_data = {"nodes": nodes, "edges": edges}
    
    # Save the detailed graph data as a JSON file
    workspace_dir = "/Users/supanus/Desktop/oneforce/extrack_scammer"
    json_path = os.path.join(workspace_dir, "knowledge_graph.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(graph_data, f, indent=2, ensure_ascii=False)
    print(f"[Agent] Saved detailed graph JSON to {json_path}")
    
    # Copy graph JSON to artifact folder
    artifact_dir = "/Users/supanus/.gemini/antigravity-ide/brain/2da58b1a-4845-4743-b79c-bd7d715bb846"
    os.makedirs(artifact_dir, exist_ok=True)
    artifact_json_path = os.path.join(artifact_dir, "knowledge_graph.json")
    import shutil
    shutil.copy2(json_path, artifact_json_path)
    print(f"[Agent] Copied graph JSON to artifact folder: {artifact_json_path}")
    
    return {
        **state,
        "graph_data": graph_data,
        "status": "Network graph built successfully"
    }

def plot_network_graph(state: AgentState) -> AgentState:
    """Node to render and save the NetworkX graph as a beautiful image matching Neo4j styling."""
    print("\n[Agent] Plotting network graph with Neo4j color scheme...")
    graph_data = state["graph_data"]
    
    # Configure Matplotlib Thai Font fallback for macOS
    plt.rcParams['font.family'] = 'Thonburi'
    plt.rcParams['axes.unicode_minus'] = False
    
    G = nx.MultiDiGraph()
    
    # Color map matching Neo4j screenshot exactly
    color_map_rules = {
        "case": "#e91e63",            # Rose Red / Pink (Case)
        "person": "#3eb489",          # Mint/Sea Green (Victim, Suspect, Defendant)
        "bank": "#ff4081",            # Hot Pink / Magenta (FinancialAccount)
        "channel": "#ff9800",         # Orange (OnlineAccount)
        "evidence": "#29b6f6",        # Sky Blue (Evidence)
        "location": "#81c784"         # Pale Light Green (Location)
    }
    
    node_colors = []
    node_sizes = []
    node_labels = {}
    
    # Add nodes to NetworkX graph
    for node in graph_data["nodes"]:
        n_id = node["id"]
        n_type = node["type"]
        label = node["label"]
        
        G.add_node(n_id, type=n_type, label=label)
        node_colors.append(color_map_rules.get(n_type, "#eeeeee"))
        node_labels[n_id] = label
        
        # Size nodes dynamically
        if n_type == "case":
            node_sizes.append(1000)
        elif n_type == "person":
            node_sizes.append(850)
        elif n_type == "bank":
            node_sizes.append(800)
        else:
            node_sizes.append(650)
            
    # Add edges
    for edge in graph_data["edges"]:
        # Pass edge properties to the graph
        G.add_edge(edge["source"], edge["target"], relation=edge["relation"], **edge.get("properties", {}))
        
    # Plotting
    plt.figure(figsize=(18, 14), dpi=150)
    plt.title("Case Knowledge Graph (Neo4j Style: Suspects separated from Defendants/Owners)", fontsize=18, fontweight='bold', pad=25)
    
    # Set dark background to match the Neo4j screenshot theme
    fig = plt.gcf()
    fig.patch.set_facecolor('#1c2025')
    ax = plt.gca()
    ax.set_facecolor('#1c2025')
    
    # Layout algorithm
    pos = nx.spring_layout(G, k=0.5, iterations=60, seed=42)
    
    # Draw Nodes
    nx.draw_networkx_nodes(G, pos, node_color=node_colors, node_size=node_sizes, alpha=0.95, edgecolors='#37474f', linewidths=1.5)
    
    # Draw Labels with white/light text for dark background
    nx.draw_networkx_labels(G, pos, labels=node_labels, font_size=8, font_color='#ffffff', font_weight='bold', font_family='Thonburi')
    
    # Draw Edges (curved for clarity)
    nx.draw_networkx_edges(G, pos, arrowstyle='-|>', arrowsize=14, edge_color='#b0bec5', width=1.2, alpha=0.7, connectionstyle='arc3,rad=0.15')
    
    # Edge Labels
    edge_labels = {}
    for u, v, data in G.edges(data=True):
        edge_labels[(u, v)] = data.get("relation", "")
        
    # Filter multi-edges to avoid overlaps
    unique_edge_labels = {k: v for k, v in edge_labels.items()}
    nx.draw_networkx_edge_labels(G, pos, edge_labels=unique_edge_labels, font_size=6, font_color='#b0bec5', font_family='Thonburi', bbox=dict(facecolor='#1c2025', alpha=0.8, edgecolor='none', pad=1))
    
    # Draw legend with custom handles
    import matplotlib.patches as mpatches
    legend_patches = [
        mpatches.Patch(color=color_map_rules["case"], label="Case (คดี)"),
        mpatches.Patch(color=color_map_rules["person"], label="Person (บุคคล: ผู้เสียหาย / ผู้ต้องสงสัย / จำเลย)"),
        mpatches.Patch(color=color_map_rules["bank"], label="FinancialAccount (บัญชีธนาคาร)"),
        mpatches.Patch(color=color_map_rules["channel"], label="OnlineAccount (ช่องทางออนไลน์)"),
        mpatches.Patch(color=color_map_rules["evidence"], label="Evidence (หลักฐาน)"),
        mpatches.Patch(color=color_map_rules["location"], label="Location (สถานที่/สภ.)")
    ]
    
    leg = plt.legend(handles=legend_patches, loc='upper left', fontsize=12, facecolor='#1c2025', edgecolor='#37474f')
    for text in leg.get_texts():
        text.set_color('white')
        
    plt.tight_layout()
    plt.axis('off')
    
    # Save file in workspace
    workspace_dir = "/Users/supanus/Desktop/oneforce/extrack_scammer"
    image_path = os.path.join(workspace_dir, "knowledge_graph.png")
    plt.savefig(image_path, format="PNG", bbox_inches='tight', facecolor='#1c2025')
    plt.close()
    
    print(f"[Agent] Saved knowledge graph image to {image_path}")
    
    # Copy the file to the artifacts directory as well
    artifact_dir = "/Users/supanus/.gemini/antigravity-ide/brain/2da58b1a-4845-4743-b79c-bd7d715bb846"
    artifact_img_path = os.path.join(artifact_dir, "knowledge_graph.png")
    import shutil
    shutil.copy2(image_path, artifact_img_path)
    print(f"[Agent] Copied graph image to artifact folder: {artifact_img_path}")
    
    return {
        **state,
        "status": "Network graph plotted and saved successfully"
    }

def upload_to_neo4j(state: AgentState) -> AgentState:
    """Node to connect to Neo4j database and populate graph data using optimized batch UNWIND queries."""
    print("\n[Agent] Uploading graph data to Neo4j database (Batch UNWIND style)...")
    graph_data = state["graph_data"]
    
    uri = os.getenv("NEO4J_URI", "bolt://localhost:7687")
    username = os.getenv("NEO4J_USERNAME", "neo4j")
    password = os.getenv("NEO4J_PASSWORD", "password")
    
    type_to_label = {
        "case": "Case",
        "person": "Person",
        "bank": "FinancialAccount",
        "channel": "OnlineAccount",
        "evidence": "Evidence",
        "location": "Location"
    }
    
    try:
        from collections import defaultdict
        
        with GraphDatabase.driver(uri, auth=(username, password)) as driver:
            with driver.session() as session:
                # 1. Create indices if they don't exist to ensure fast merges/matches
                print("[Neo4j] Ensuring indexes exist for all node types...")
                for label in type_to_label.values():
                    index_query = f"CREATE INDEX {label.lower()}_id_idx IF NOT EXISTS FOR (n:{label}) ON (n.id)"
                    session.run(index_query)
                
                # 2. Clear existing nodes related to these cases to prevent duplicates
                print("[Neo4j] Cleaning up existing nodes linked to these cases...")
                case_ids = [n["properties"].get("case_id") for n in graph_data["nodes"] if n["type"] == "case"]
                if case_ids:
                    session.run("""
                    MATCH (c:Case)
                    WHERE c.case_id IN $case_ids
                    DETACH DELETE c
                    """, case_ids=case_ids)
                    
                    # Clean up orphaned Person, Accounts, Locations, Evidence (no links to Case left)
                    session.run("""
                    MATCH (n)
                    WHERE (n:Person OR n:FinancialAccount OR n:OnlineAccount OR n:Evidence OR n:Location)
                      AND NOT (n)-[]-(:Case)
                    DETACH DELETE n
                    """)
                
                # 3. Group and Batch Upload Nodes
                print("[Neo4j] Batch uploading nodes...")
                nodes_by_label = defaultdict(list)
                for node in graph_data["nodes"]:
                    label = type_to_label.get(node["type"], "Entity")
                    props = dict(node.get("properties", {}))
                    props["id"] = node["id"]
                    props["label"] = node["label"]
                    nodes_by_label[label].append(props)
                    
                for label, batch in nodes_by_label.items():
                    print(f"  - Uploading {len(batch)} nodes for label '{label}'...")
                    session.run(f"""
                    UNWIND $batch AS row
                    MERGE (n:{label} {{id: row.id}})
                    SET n += row
                    """, batch=batch)
                    
                # 4. Group and Batch Upload Edges
                print("[Neo4j] Batch uploading relationships...")
                nodes_dict = {node["id"]: node for node in graph_data["nodes"]}
                edges_by_group = defaultdict(list)
                
                for edge in graph_data["edges"]:
                    source_id = edge["source"]
                    target_id = edge["target"]
                    relation = edge["relation"]
                    props = edge.get("properties", {})
                    
                    src_label = type_to_label.get(nodes_dict[source_id]["type"], "Entity")
                    tgt_label = type_to_label.get(nodes_dict[target_id]["type"], "Entity")
                    
                    key = (src_label, tgt_label, relation)
                    edges_by_group[key].append({
                        "source_id": source_id,
                        "target_id": target_id,
                        "properties": props
                    })
                    
                for (src_label, tgt_label, relation), batch in edges_by_group.items():
                    print(f"  - Uploading {len(batch)} relationships of type: ({src_label})-[{relation}]->({tgt_label})...")
                    session.run(f"""
                    UNWIND $batch AS row
                    MATCH (a:{src_label} {{id: row.source_id}})
                    MATCH (b:{tgt_label} {{id: row.target_id}})
                    MERGE (a)-[r:{relation}]->(b)
                    SET r += row.properties
                    """, batch=batch)
                    
        print("✔ [Neo4j] Graph successfully uploaded to Neo4j in batches!")
        return {**state, "status": "Graph successfully uploaded to Neo4j"}
        
    except Exception as e:
        print(f"⚠ [Warning] Could not upload graph to Neo4j: {e}")
        print("Ensure your Neo4j docker container is running and connection details in .env are correct.")
        return {**state, "status": f"Graph built, but Neo4j upload failed/skipped: {e}"}
